resource "local_file" "ansible_vars_tf" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration. This file is created from the ansible-vars.tf when terraform apply is run for Hashicorp Vault

    vault_repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    
    # src= relative to the path of the install_vault.yml playbook
    vault_config_location_src: templates/vault.j2
    vault_config_location_dest: /etc/vault.d/vault.hcl
    root_token_dir_output: 
    recovery_keys_dir_output: 
    tf_vault_kms_key: ${aws_kms_key.vault-unseal.id}
    aws_secret_key: 
    aws_access_key: 

    DOC
  filename = "../roles/install-vault/vars/main.yml"
}